name: 'my first container action'
description: 'A github'
author: 'Mohit Singh'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: "Awesome github"
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
